# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: College quizbowl calendar
email: your-email@example.com
description: College quizbowl calendar
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://collegequizbowlcalendar.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  quizbowl
google_analytics: UA-8654955-6
timezone: UTC

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
plugins:
  - jekyll-timeago
  - jekyll-redirect-from
# - jekyll-feed
kramdown:
  footnote_backlink: "&#x2934;"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

jekyll_timeago:
  depth: 1 # Level of detail
  today: 'same day'
  yesterday: '1 day'
  tomorrow: '1 day'
  and: 'and'
  suffix: ''
  prefix: ''
  suffix_future: ''
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
